/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users.index'
import { Route as UsersIdImport } from './routes/users.$id'
import { Route as UsersIdIndexImport } from './routes/users.$id.index'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)

const UsersIdRoute = UsersIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)

const UsersIdIndexRoute = UsersIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdImport
      parentRoute: typeof UsersImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof UsersImport
    }
    '/users/$id/': {
      id: '/users/$id/'
      path: '/'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof UsersIdIndexImport
      parentRoute: typeof UsersIdImport
    }
  }
}

// Create and export the route tree

interface UsersIdRouteChildren {
  UsersIdIndexRoute: typeof UsersIdIndexRoute
}

const UsersIdRouteChildren: UsersIdRouteChildren = {
  UsersIdIndexRoute: UsersIdIndexRoute,
}

const UsersIdRouteWithChildren =
  UsersIdRoute._addFileChildren(UsersIdRouteChildren)

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRouteWithChildren
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRouteWithChildren,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersRouteWithChildren
  '/users/$id': typeof UsersIdRouteWithChildren
  '/users/': typeof UsersIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users': typeof UsersIndexRoute
  '/users/$id': typeof UsersIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/users': typeof UsersRouteWithChildren
  '/users/$id': typeof UsersIdRouteWithChildren
  '/users/': typeof UsersIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users' | '/users/$id' | '/users/' | '/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users' | '/users/$id'
  id: '__root__' | '/' | '/users' | '/users/$id' | '/users/' | '/users/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRoute: typeof UsersRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users": {
      "filePath": "users.tsx",
      "children": [
        "/users/$id",
        "/users/"
      ]
    },
    "/users/$id": {
      "filePath": "users.$id.tsx",
      "parent": "/users",
      "children": [
        "/users/$id/"
      ]
    },
    "/users/": {
      "filePath": "users.index.tsx",
      "parent": "/users"
    },
    "/users/$id/": {
      "filePath": "users.$id.index.tsx",
      "parent": "/users/$id"
    }
  }
}
ROUTE_MANIFEST_END */
